### PR TITLE
The smart way

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
;-)

### CODE REVIEW

**Comment by 0xFACE** [comment]
Thanks ;-)
I'm not bash hacker, but there seems to be problem with long strings formating.
There is always space after 60 char: 

20 BTPOKE LIM_DISC_ADV_INT_MIN, T
3230204254504f4b45204c494d5f444953435f4144565f494e545f4d494e 2c20540d

**Comment by 0x2b3bfa0** [comment]
@0xFACE: Ok, I never thought that I should put a space. Fixing... :smiling_imp:

**Comment by 0xFACE** [comment]
Sorry for my English ;-)
This space is unwanted. Proper string conversion should look like this:
20 BTPOKE LIM_DISC_ADV_INT_MIN, T
3230204254504f4b45204c494d5f444953435f4144565f494e545f4d494e2c20540d

**Comment by 0x2b3bfa0** [comment]
# And now?

**Comment by 0xFACE** [comment]
Thanks, it works for me now ;-)

**Comment by 0x2b3bfa0** [comment]
@0xFACE: So, should it be merged?

Don't forgot to edit the usage string and remove the echo before `gatttool` and the comment at the end of the line.

**Comment by 0xFACE** [comment]
Sure. Sorry, I'm git beginner ;-)

**Comment by 0x2b3bfa0** [comment]
I wouldn't know even how to merge ;-). Don't worry!

**Comment by 0x2b3bfa0** [comment]
Please see the next PR ;-)

**Pull request merged**
