### PR TITLE
Fix #3, improve upload speed and code cleanup

### LINKED ISSUE #3: Add a progress bar to upload process
Wouldn't be a good idea to add a progress bar to the upload process?

I don't have a BLE capable computer, however if you record for me a asciinema of the uploading process, I could make a progress bar for it.

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**

### CODE REVIEW

**Comment by 0xFACE** [comment]
Comparison: 
https://asciinema.org/a/1vsrdt1ndnu6cjwbxcgi2360t

**Comment by 0x2b3bfa0** [comment]
@0xFACE: So it's faster now? :smile: Now it uploads the code per 90byte chunks and not per lines.

**Comment by 0xFACE** [comment]
Something went wrong ...
After "big chunk" PR I can't upload any file. 

Strange thing, I recorded successfully asciinema and now bbload doesn't work. The old version does.
Something wrong with my device or I just mess something.

It looks like my device is always dying after 2nd data chunk.

**Comment by 0x2b3bfa0** [comment]
@0xFACE: Maybe the device expects chunks ending in 0x0d (`\r`) and I can't optimize the upload by chunks. However, this seems me so strange. Could you send me asciinema of this? Sorry :worried:

Also, I'm setting up the Makefile :smile:

I'll go asleep. Tomorrow I'll continue.

**Comment by 0xFACE** [comment]
http://asciinema.org/a/5wb66ejv85n2yvdlehtf7m6el

**Comment by 0x2b3bfa0** [comment]
@0xFACE: Can you try to determine where is the fail? The only CC2540/2541 device I have is a counterfeit HM-10 without the 32 xtal. So it's a no-go for now.

**Pull request merged**
